"""add user_uid to jobs

Revision ID: 55273243745f
Revises: df663189ea55
Create Date: 2026-07-10 13:57:02.109012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55273243745f'
down_revision: Union[str, Sequence[str], None] = 'df663189ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_uid'], ['uid'])
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_uid')
    # ### end Alembic commands ###
