"""add role to user model

Revision ID: df663189ea55
Revises: 
Create Date: 2026-07-10 12:52:02.311524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df663189ea55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('jobs', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
